#!/usr/bin/env bash

set -euo pipefail

debug_mode='off'
if [[ "${BUILDKITE_PLUGIN_REATTACH_HEAD_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  debug_mode='on'
  set -x
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/shared.bash"

plugin_prompt_and_must_run git fetch origin ${BUILDKITE_BRANCH}
plugin_prompt_and_must_run git checkout -B ${BUILDKITE_BRANCH}
plugin_prompt_and_must_run git branch -u origin/${BUILDKITE_BRANCH}
plugin_prompt_and_must_run git config branch.${BUILDKITE_BRANCH}.remote origin
plugin_prompt_and_must_run git config branch.${BUILDKITE_BRANCH}.merge refs/heads/${BUILDKITE_BRANCH}
